version: '2'
services:
  web:
    container_name: www
    build: ./server/php
    ports:
     - "80:80"
    volumes:
     - ./app/:/var/www/app
    links:
     - db
     
  db:
    container_name: mysql
    image: mysql
    ports:
     - "3306:3306"
    volumes:
     - ./mysql:/var/lib/mysql
    environment:
     MYSQL_ROOT_PASSWORD: "docker" 
     MYSQL_DATABASE: "docker"
  
  phpmyadmin:
    container_name: sqladmin
    image: phpmyadmin/phpmyadmin
    links:
     - db
    environment:
     PMA_HOST: db
     PMA_PORT: 3306
    ports:
     - '8080:80'
  
